# Ghost configuration for Docker Compose environment
app:
  id: "ghost-app"
  name: "Ghost Application"
  description: "A Ghost Application"
  version: "1.0.0"

core:
  mode: "development"
  logsPath: "logs"
  logLevel: "Debug"
  dataPath: "data"
  appsPath: "ghosts"
  listenPort: 5000
  healthCheckInterval: "00:00:30"
  metricsInterval: "00:00:05"
  settings:
    autoGhostFather: "true"
    autoMonitor: "true"
  watchPaths: [ ]
  watchIgnore:
    - "*.log"
    - "*.tmp"
  ghostFatherHost: "localhost"
  ghostFatherPort: 5000
  maxRetries: 3
  retryDelay: "00:00:01"
  useInMemoryDatabase: false

redis:
  enabled: true
  connectionString: "localhost:6379"
  database: 0
  useSsl: false
  connectRetry: 3
  connectTimeout: "00:00:05"
  syncTimeout: "00:00:05"
  commandTimeout: "00:00:10"
  keyPrefix: ""

postgres:
  enabled: true
  connectionString: "Host=localhost;Port=5432;Database=ghost;Username=ghost;Password=ghost;"
  maxPoolSize: 100
  minPoolSize: 5
  prewarmConnections: false
  connectionLifetime: "00:30:00"
  connectionIdleLifetime: "00:05:00"
  commandTimeout: 30
  enableParameterLogging: false
  schema: "public"
  enablePooling: true

caching:
  enabled: true
  useL1Cache: true
  useL2Cache: true
  defaultExpiration: "00:05:00"
  defaultL1SlidingExpiration: "00:01:00"
  defaultL1Expiration: "00:05:00"
  defaultL2Expiration: "00:30:00"
  maxL1CacheItems: 10000
  maxL1CacheSizeBytes: 104857600
  cachePath: "cache"
  compressItems: false
  compressionThreshold: 1024

resilience:
  enableRetry: true
  retryCount: 3
  retryBaseDelayMs: 100
  enableCircuitBreaker: true
  circuitBreakerThreshold: 5
  circuitBreakerDurationMs: 30000
  timeoutMs: 30000
  enableBulkhead: false

security:
  enableEncryption: false
  encryptionKey: ""
  encryptionIV: ""
  encryptionAlgorithm: "AES"
  enableAudit: false
  enableAccessControl: false
  auditLogPath: "logs/audit"
  auditLogRetentionDays: 90

observability:
  enabled: true
  logLevel: "Debug"
  enableConsoleLogging: true
  enableFileLogging: true
  enableMetrics: true
  enableTracing: false
  enableHealthChecks: true
  logsPath: "logs"
  logRetentionDays: 7
  metricsIntervalSeconds: 15
  healthCheckIntervalSeconds: 30
  enableStructuredLogging: true
  tracingSamplingRate: 0.1

modules: { }
